import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { fileURLToPath } from 'url';
// Generated by `npm run sync:reports`: stem + sha256 for every source fundus
// image. This is what lets uploads be matched by content without deploying
// 46MB of PNGs alongside the app.
//
// Read with fs rather than `import ... from './sourceImages.json'` so the
// module also loads under plain Node ESM (scripts, tests), not just through
// Next's bundler. next.config.js traces it into the serverless bundle.
function loadSourceManifest() {
  // Each candidate is resolved inside its own try: under Next's bundler
  // `fileURLToPath` is a shim that throws on anything but a plain string, and
  // that must not take the whole lookup down.
  const candidates = [
    () => path.join(process.cwd(), 'lib', 'sourceImages.json'),
    () => fileURLToPath(String(new URL('./sourceImages.json', import.meta.url))),
  ];

  for (const resolve of candidates) {
    try {
      return JSON.parse(fs.readFileSync(resolve(), 'utf8'));
    } catch {
      // not there, or not resolvable in this runtime — try the next
    }
  }
  return [];
}

// ─────────────────────────────────────────────────────────────────────────
// Pre-computed screening reports produced by the MATLAB/ML pipeline live
// outside this app. When a user uploads a left/right pair that belongs to
// one of the demo sets, we hand back that set's already-generated PDF and
// overlay images instead of the placeholder report.
//
// Point these at a different folder with REPORTS_DIR / SETS_DIR in .env.local
// — nothing else needs to change.
// ─────────────────────────────────────────────────────────────────────────

// The pipeline's own output folder, used when nothing else is configured.
const PIPELINE_REPORTS_DIR =
  'C:\\Pranav\\college\\sih\\SIH_MathWorks_2026\\reports';

// Resolution order, most explicit first:
//   1. REPORTS_DIR, when it's set and actually exists
//   2. reports/ in this repo — the copy that deploys to Vercel, and what dev
//      uses by default so local matches production
//   3. the pipeline's folder on this machine
function pickDir(configured, repoRelative, fallback) {
  if (configured && fs.existsSync(configured)) return configured;
  const inRepo = path.join(process.cwd(), repoRelative);
  if (fs.existsSync(inRepo)) return inRepo;
  return configured || fallback;
}

export const REPORTS_DIR = pickDir(
  process.env.REPORTS_DIR,
  'reports',
  PIPELINE_REPORTS_DIR
);

// The source fundus images the reports were generated from. Used to match an
// upload by file content (sha256), which survives renaming. Not needed in a
// deployment — sourceImages.json carries the hashes instead (see below).
export const SETS_DIR = pickDir(
  process.env.SETS_DIR,
  'public/demo-sets',
  path.join(path.dirname(PIPELINE_REPORTS_DIR), 'sets')
);

const IMAGE_EXTS = new Set(['.png', '.jpg', '.jpeg']);
const OVERLAY_RE = /^(left|right)_(.+)_(attention|panels)\.png$/i;
const ID_CODE_RE = /([0-9a-f]{12})/i;
const CACHE_TTL_MS = 10_000; // re-scan the folders every 10s so new runs show up

// Bumped whenever the shape or the meaning of a stored `analysis` changes, so
// submissions saved by an older version get re-matched on read instead of
// showing stale findings. v2: grades now come from the report, not file names.
export const ANALYSIS_SCHEMA_VERSION = 2;

export const GRADE_LABELS = {
  0: 'No DR',
  1: 'Mild NPDR',
  2: 'Moderate NPDR',
  3: 'Severe NPDR',
  4: 'Proliferative DR',
};

// ─────────────────────────────────────────────────────────────────────────
// What each screening report actually concludes, transcribed from the PDFs.
//
// This has to be stated explicitly because the two numbers in play disagree.
// A file called `two_grade1_left_...` carries APTOS's ground-truth label
// (grade 1) — but the report for that set says the model graded it Moderate
// NPDR (level 2). The report is the system's own output and the thing the
// user is handed, so the UI must follow it, never the file name.
//
// Only set_five's ground-truth label matches its report; every other set
// differs by a level.
//
// To refresh after re-running the pipeline: open each screening_report.pdf
// and copy the verdict line ("FLAGGED FOR REVIEW — worst eye X: <label>
// (level N), referable probability P%") and the two per-eye headings
// ("Left eye — <label> (level N)").
// ─────────────────────────────────────────────────────────────────────────
const REPORT_FINDINGS = {
  set_one: {
    flagged: true,
    worstEye: 'left',
    referableProbability: 0.47,
    left: { grade: 1, referable: true, probability: 0.47 },
    right: { grade: 0, referable: false, probability: 0.33 },
  },
  set_two: {
    flagged: true,
    worstEye: 'left',
    referableProbability: 0.53,
    left: { grade: 2, referable: true, probability: 0.53 },
    right: { grade: 2, referable: true, probability: 0.52 },
  },
  set_three: {
    flagged: true,
    worstEye: 'right',
    referableProbability: 0.84,
    left: { grade: 2, referable: true, probability: 0.62 },
    right: { grade: 3, referable: true, probability: 0.84 },
  },
  set_four: {
    flagged: true,
    worstEye: 'left',
    referableProbability: 0.95,
    left: { grade: 4, referable: true, probability: 0.95 },
    right: { grade: 4, referable: true, probability: 0.99 },
  },
  set_five: {
    flagged: true,
    worstEye: 'left',
    referableProbability: 0.93,
    left: { grade: 4, referable: true, probability: 0.93 },
    right: { grade: 4, referable: true, probability: 0.99 },
  },
  set_six: {
    flagged: true,
    worstEye: 'right',
    referableProbability: 0.7,
    left: { grade: 1, referable: true, probability: 0.5 },
    right: { grade: 3, referable: true, probability: 0.7 },
  },
  demo_patient: {
    flagged: true,
    worstEye: 'left',
    referableProbability: 0.47,
    left: { grade: 1, referable: true, probability: 0.47 },
    right: { grade: 0, referable: false, probability: 0.33 },
  },
};

let cache = { at: 0, index: null };
const hashCache = new Map(); // absolute file path -> sha256

function safeReadDir(dir) {
  try {
    return fs.readdirSync(dir, { withFileTypes: true });
  } catch {
    return [];
  }
}

// ── Source images ────────────────────────────────────────────────────────
// Indexes every source fundus image by stem, by the 12-hex id code in its
// name, and by sha256. The manifest is the primary source (it works in a
// deployment where the images themselves aren't present); SETS_DIR is then
// scanned for anything the manifest doesn't already cover.
function buildSourceIndex() {
  const byStem = new Map();
  const byIdCode = new Map();
  const byHash = new Map();

  function add(entry) {
    byStem.set(entry.stem, entry);
    const id = entry.idCode || entry.stem.match(ID_CODE_RE)?.[1]?.toLowerCase();
    if (id) byIdCode.set(id, entry);
    if (entry.sha256) byHash.set(entry.sha256.toLowerCase(), entry);
  }

  const sourceManifest = loadSourceManifest();
  for (const item of Array.isArray(sourceManifest) ? sourceManifest : []) {
    if (!item?.stem) continue;
    const entry = {
      stem: String(item.stem).toLowerCase(),
      idCode: item.idCode ? String(item.idCode).toLowerCase() : null,
      sha256: item.sha256 ? String(item.sha256).toLowerCase() : null,
      path: null,
    };
    add(entry);
    // The published images have the grade stripped from their names, but the
    // pipeline's originals still carry it — accept either spelling.
    if (item.sourceStem && item.sourceStem !== entry.stem) {
      byStem.set(String(item.sourceStem).toLowerCase(), entry);
    }
  }

  function addFile(fullPath) {
    const ext = path.extname(fullPath).toLowerCase();
    if (!IMAGE_EXTS.has(ext)) return;
    const stem = path.basename(fullPath, ext).toLowerCase();
    const existing = byStem.get(stem);
    if (existing) {
      existing.path = fullPath; // manifest entry, now backed by a real file
      return;
    }
    add({ stem, idCode: null, sha256: null, path: fullPath });
  }

  for (const entry of safeReadDir(SETS_DIR)) {
    const full = path.join(SETS_DIR, entry.name);
    if (entry.isDirectory()) {
      for (const child of safeReadDir(full)) {
        if (child.isFile()) addFile(path.join(full, child.name));
      }
    } else if (entry.isFile()) {
      addFile(full);
    }
  }

  return { byStem, byIdCode, byHash };
}

// grade per id code, read from the pipeline's manifest when it is available.
function readManifestGrades() {
  const grades = new Map();
  const manifest = path.join(SETS_DIR, 'sets_manifest.csv');
  let text;
  try {
    text = fs.readFileSync(manifest, 'utf8');
  } catch {
    return grades;
  }
  const lines = text.split(/\r?\n/).filter(Boolean);
  if (lines.length < 2) return grades;
  const header = lines[0].split(',').map((c) => c.replace(/"/g, '').trim());
  const gradeCol = header.indexOf('grade');
  const idCol = header.indexOf('id_code');
  if (gradeCol === -1 || idCol === -1) return grades;
  for (const line of lines.slice(1)) {
    const cells = line.split(',').map((c) => c.replace(/"/g, '').trim());
    const id = cells[idCol]?.toLowerCase();
    const grade = Number(cells[gradeCol]);
    if (id && Number.isFinite(grade)) grades.set(id, grade);
  }
  return grades;
}

// ── Report folders ───────────────────────────────────────────────────────
// Each subfolder of REPORTS_DIR is one set: a screening PDF plus attention /
// panel overlays for the left and right eye.
function buildReportIndex() {
  const sets = [];

  for (const dirEntry of safeReadDir(REPORTS_DIR)) {
    if (!dirEntry.isDirectory()) continue;
    const setId = dirEntry.name;
    const dir = path.join(REPORTS_DIR, setId);
    const files = safeReadDir(dir)
      .filter((f) => f.isFile())
      .map((f) => f.name);

    const pdf =
      files.find((f) => f.toLowerCase() === 'screening_report.pdf') ||
      files.find((f) => f.toLowerCase().endsWith('.pdf'));
    if (!pdf) continue;

    const eyes = { left: {}, right: {} };
    for (const file of files) {
      const m = file.match(OVERLAY_RE);
      if (!m) continue;
      const eye = m[1].toLowerCase();
      const stem = m[2].toLowerCase();
      const kind = m[3].toLowerCase();
      eyes[eye].stem = stem;
      eyes[eye][kind] = `${setId}/${file}`;
    }

    if (!eyes.left.stem && !eyes.right.stem) continue;

    const stems = [eyes.left.stem, eyes.right.stem].filter(Boolean);
    const gradeFromName = stems
      .map((s) => s.match(/grade(\d)/i))
      .find(Boolean);

    // What the report concludes, and — separately — the dataset label baked
    // into the file name. They disagree for most sets; `grade` is the one the
    // UI shows, because it's what the PDF in the user's hand says.
    const findings = REPORT_FINDINGS[setId] || null;
    const reportGrade = findings
      ? Math.max(findings.left.grade, findings.right.grade)
      : null;

    sets.push({
      setId,
      pdf: `${setId}/${pdf}`,
      eyes,
      stems,
      idCodes: stems
        .map((s) => s.match(ID_CODE_RE)?.[1]?.toLowerCase())
        .filter(Boolean),
      findings,
      grade: reportGrade,
      groundTruthGrade: gradeFromName ? Number(gradeFromName[1]) : null,
    });
  }

  // Named sets win over ad-hoc folders (e.g. demo_patient, which reuses the
  // same images as set_one) when both match the same upload.
  sets.sort((a, b) => {
    const rank = (s) => (/^set[_-]/i.test(s.setId) ? 0 : 1);
    return rank(a) - rank(b) || a.setId.localeCompare(b.setId);
  });

  return sets;
}

function getIndex() {
  const now = Date.now();
  if (cache.index && now - cache.at < CACHE_TTL_MS) return cache.index;

  const sets = buildReportIndex();
  const source = buildSourceIndex();
  const manifestGrades = readManifestGrades();

  // Fill in any dataset label the folder names didn't reveal (demo_patient)
  // from the manifest, via the id code. Only ever the ground-truth label —
  // `grade` always comes from the report itself.
  for (const set of sets) {
    if (set.groundTruthGrade === null) {
      for (const id of set.idCodes) {
        if (manifestGrades.has(id)) {
          set.groundTruthGrade = manifestGrades.get(id);
          break;
        }
      }
    }
    // No transcribed findings for this folder (a set added since) — fall back
    // to the dataset label rather than showing nothing.
    if (set.grade === null) set.grade = set.groundTruthGrade;
  }

  const index = { sets, source, manifestGrades };
  cache = { at: now, index };
  return index;
}

function sha256OfFile(filePath) {
  const cached = hashCache.get(filePath);
  if (cached) return cached;
  try {
    const hash = crypto
      .createHash('sha256')
      .update(fs.readFileSync(filePath))
      .digest('hex');
    hashCache.set(filePath, hash);
    return hash;
  } catch {
    return null;
  }
}

// Resolves one uploaded eye image to a source image stem.
// meta = { fileName, sha256 } — both optional, either is enough.
function resolveStem(meta, index) {
  if (!meta) return null;

  // 1. Exact content match (rename-proof). The manifest gives this for free;
  // fall back to hashing files on disk for anything it doesn't cover.
  if (meta.sha256) {
    const wanted = String(meta.sha256).toLowerCase();
    const hit = index.source.byHash.get(wanted);
    if (hit) return { stem: hit.stem, matchedBy: 'content' };

    for (const entry of index.source.byStem.values()) {
      if (entry.sha256 || !entry.path) continue; // already covered above
      if (sha256OfFile(entry.path) === wanted) {
        return { stem: entry.stem, matchedBy: 'content' };
      }
    }
  }

  // 2. Fall back to the file name: exact stem, then the embedded id code.
  if (meta.fileName) {
    const stem = path
      .basename(String(meta.fileName))
      .replace(/\.[^.]+$/, '')
      .toLowerCase();
    if (index.source.byStem.has(stem)) {
      return { stem, matchedBy: 'filename' };
    }
    const id = stem.match(ID_CODE_RE)?.[1]?.toLowerCase();
    if (id) {
      const entry = index.source.byIdCode.get(id);
      if (entry) return { stem: entry.stem, matchedBy: 'filename' };
      // The source folder may be missing — the report file names carry the
      // id too, so still try to match on that alone.
      return { stem: null, idCode: id, matchedBy: 'filename' };
    }
  }

  return null;
}

function setMatchesEye(set, eye, resolved) {
  if (!resolved) return false;
  const stem = set.eyes[eye]?.stem;
  if (!stem) return false;
  if (resolved.stem && stem === resolved.stem) return true;
  const id = resolved.idCode || resolved.stem?.match(ID_CODE_RE)?.[1];
  if (!id) return false;
  return stem.includes(id.toLowerCase());
}

export function reportFileUrl(relativePath) {
  return `/api/reports/${relativePath
    .split('/')
    .map(encodeURIComponent)
    .join('/')}`;
}

/**
 * Matches an uploaded left/right pair against the pre-generated report sets.
 * Returns the analysis object stored on the submission, or null when the
 * upload isn't one of the known demo images.
 */
export function matchReportSet(leftMeta, rightMeta) {
  const index = getIndex();
  if (!index.sets.length) return null;

  const left = resolveStem(leftMeta, index);
  const right = resolveStem(rightMeta, index);
  if (!left && !right) return null;

  let best = null;
  for (const set of index.sets) {
    const leftHit = setMatchesEye(set, 'left', left);
    const rightHit = setMatchesEye(set, 'right', right);
    const score = (leftHit ? 1 : 0) + (rightHit ? 1 : 0);
    if (!score) continue;
    if (!best || score > best.score) best = { set, score, leftHit, rightHit };
    if (best.score === 2) break; // both eyes agree — nothing can beat that
  }
  if (!best) return null;

  const { set, leftHit, rightHit } = best;
  const matchedBy =
    [leftHit && left?.matchedBy, rightHit && right?.matchedBy].find(Boolean) ||
    'filename';

  const eyeBlock = (eye, hit) => {
    const e = set.eyes[eye] || {};
    const f = set.findings?.[eye] || null;
    return {
      matched: Boolean(hit),
      sourceStem: e.stem || null,
      attentionUrl: e.attention ? reportFileUrl(e.attention) : null,
      panelsUrl: e.panels ? reportFileUrl(e.panels) : null,
      // Straight from the report for this eye.
      grade: f ? f.grade : null,
      gradeLabel: f ? GRADE_LABELS[f.grade] || null : null,
      referable: f ? f.referable : null,
      probability: f ? f.probability : null,
    };
  };

  const verdict = set.findings
    ? {
        flagged: set.findings.flagged,
        worstEye: set.findings.worstEye,
        grade: set.grade,
        gradeLabel: GRADE_LABELS[set.grade] || null,
        referableProbability: set.findings.referableProbability,
      }
    : null;

  return {
    setId: set.setId,
    setLabel: set.setId.replace(/[_-]/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase()),
    // The report's grade — the worst of the two eyes. Not the dataset label.
    grade: set.grade,
    gradeLabel: set.grade !== null ? GRADE_LABELS[set.grade] || null : null,
    groundTruthGrade: set.groundTruthGrade,
    verdict,
    matchedBy,
    matchedEyes: [leftHit && 'left', rightHit && 'right'].filter(Boolean),
    reportPdf: set.pdf,
    reportUrl: reportFileUrl(set.pdf),
    left: eyeBlock('left', leftHit),
    right: eyeBlock('right', rightHit),
    schemaVersion: ANALYSIS_SCHEMA_VERSION,
    matchedAt: new Date().toISOString(),
  };
}

/**
 * Re-runs the match for a submission whose stored analysis predates the
 * current schema, and saves the result. Submissions completed before the
 * grade source changed would otherwise keep showing the old value.
 * Returns true when the document was updated.
 */
export async function refreshStaleAnalysis(submission) {
  if (!submission?.analysis) return false;
  if (submission.analysis.schemaVersion === ANALYSIS_SCHEMA_VERSION) return false;

  const plain = (meta) =>
    meta && typeof meta.toObject === 'function' ? meta.toObject() : meta;

  const fresh = matchReportSet(
    plain(submission.leftEyeMeta),
    plain(submission.rightEyeMeta)
  );
  if (!fresh) return false;

  submission.analysis = fresh;
  submission.markModified('analysis');
  await submission.save();
  return true;
}

/** Absolute path for a file served out of REPORTS_DIR, or null if it escapes. */
export function resolveReportFile(relativeSegments) {
  const rootDir = path.resolve(REPORTS_DIR);
  const target = path.resolve(rootDir, ...relativeSegments);
  const withSep = rootDir.endsWith(path.sep) ? rootDir : rootDir + path.sep;
  if (!target.startsWith(withSep)) return null;
  return target;
}

/** Quick health check used by the dev-facing status endpoint. */
export function describeReportsConfig() {
  const index = getIndex();
  return {
    reportsDir: REPORTS_DIR,
    setsDir: SETS_DIR,
    reportsDirExists: fs.existsSync(REPORTS_DIR),
    setsDirExists: fs.existsSync(SETS_DIR),
    usingRepoCopy: REPORTS_DIR === path.join(process.cwd(), 'reports'),
    hashedSourceImages: index.source.byHash.size,
    sets: index.sets.map((s) => ({
      setId: s.setId,
      grade: s.grade,
      gradeLabel: s.grade !== null ? GRADE_LABELS[s.grade] || null : null,
      left: s.eyes.left?.stem || null,
      right: s.eyes.right?.stem || null,
      pdf: s.pdf,
    })),
    sourceImages: index.source.byStem.size,
  };
}
